CREATE PROCEDURE [dbo].[delete_cartItems]
	@cartId int=NULL
AS
BEGIN
	IF @cartId IS NOT NULL AND @cartId>0 BEGIN
		BEGIN TRANSACTION
		BEGIN TRY
			DELETE FROM dbo.CartItems WHERE cartId=@cartId
			COMMIT TRANSACTION
		END TRY
		BEGIN CATCH
			ROLLBACK TRANSACTION
		END CATCH
	END
END
